"""Add is_hard_deposit flag to transactions

Revision ID: 32d5f64be781
Revises: 6d767c78747c
Create Date: 2024-11-26 06:13:49.588892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d5f64be781'
down_revision: Union[str, None] = '6d767c78747c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
