"""Add transactions table

Revision ID: bcd10d788ac5
Revises: 02d48c687b69
Create Date: 2024-11-21 19:46:13.519183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd10d788ac5'
down_revision: Union[str, None] = '02d48c687b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_system', sa.Enum('fps', 'sberpay', 'yoomoney', 'card', 'ptop', 'internal', name='paymentsystem'), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', 'BONUS', 'REFERRAL', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('from_account', sa.String(), nullable=True),
    sa.Column('to_account', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='transactionstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
