"""Add is_hard_deposit column to transactions

Revision ID: e0656eed9205
Revises: 32d5f64be781
Create Date: 2024-11-26 06:21:13.549051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0656eed9205'
down_revision: Union[str, None] = '32d5f64be781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_hard_deposit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_hard_deposit')
    # ### end Alembic commands ###
